# Generated by Django 5.2.3 on 2025-06-22 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_opened', models.DateField()),
                ('working_hours', models.CharField(default='09:00am - 10:00pm', max_length=20)),
                ('type', models.CharField(choices=[('FF', 'Fast Food'), ('AS', 'Asian'), ('IT', 'Italian'), ('GH', 'Ghanaian')], default='', max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
