# Generated by Django 5.2.3 on 2025-06-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(blank=True, choices=[('FF', 'Fast Food'), ('AS', 'Asian'), ('IT', 'Italian'), ('GH', 'Ghanaian')], max_length=2, null=True),
        ),
    ]
